web/views/panel.py
from typing import List

import httpx
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from config import config
from db.pg import db_session
from models.bots import Bots
from models.connectors import (
    GoodgameStreams,
    Twitch,
    TwitchActions,
    TwitchActionsAttachments,
    VkPlayLive,
)
from models.webhooks import Webhooks
from web.shared_loop import loop
from web.views import tools
from web.views.forms.bot import NewBotForm
from web.views.forms.new_twitch import NewTwitchSource
from web.views.forms.vkplay import BasicStreamForm

app = Blueprint("panel", __name__)


@app.route("/panel/")
@login_required
def index():
    return render_template("panel.html", current_user=current_user)


@app.route("/panel/source/twitch/")
@login_required
def twitch_list():
    limit = request.args.get("limit") or 100
    offset = request.args.get("offset") or 0
    query = (
        db_session.query(Twitch)
        .filter(Twitch.author_id == current_user.id)
        .order_by(Twitch.created_at.desc())
    )
    if limit:
        query = query.limit(limit)
    if offset:
        query = query.offset(offset)

    twitch_sources: List[Twitch] = query.all()

    if twitch_sources:
        tools.sync_webhook_statuses()

    webhook_statuses = {}
    for twitch in twitch_sources:
        webhook: Webhooks = (
            db_session.query(Webhooks)
            .filter(
                Webhooks.twitch_id == twitch.id, Webhooks.tgbot_id == twitch.tgbot_id
            )
            .first()
        )
        if not webhook:
            continue

        webhook_statuses[
            f"{webhook.twitch_id}_{webhook.tgbot_id}"
        ] = webhook.twitch_webhook_status

    return render_template(
        "panel/panel_list_twitch.html",
        current_user=current_user,
        twitch_sources=twitch_sources,
        webhook_statuses=webhook_statuses,
    )


@app.route("/panel/source/twitch/new/")
@login_required
def new_twitch_source():
    form = NewTwitchSource()
    form.bot.choices = tools.get_bots_choices(current_user_id=current_user.id)
    form_action = url_for("panel.new_twitch_source_post")
    return render_template(
        "panel/panel_form_twitch.html",
        current_user=current_user,
        form=form,
        form_action=form_action,
        is_new=True,
    )


@app.route("/panel/twitch/new/", methods=["POST"])
@login_required
def new_twitch_source_post():
    form = NewTwitchSource(request.form)
    form.bot.choices = tools.get_bots_choices(current_user_id=current_user.id)
    form_action = url_for("panel.new_twitch_source_post")
    if not form.validate():
        return (
            render_template(
                "panel/panel_form_twitch.html",
                current_user=current_user,
                form=form,
                form_action=form_action,
                is_new=True,
            ),
            422,
        )

    filename = None

    broadcaster = loop.run_until_complete(
        tools.get_broadcaster(form.twitch_channel_name.data)
    )
    if not broadcaster:
        flash("Ваш broadcaster.id (twitch) не найден", category="danger")
        return (
            render_template(
                "panel/panel_form_twitch.html",
                current_user=current_user,
                form=form,
                form_action=form_action,
                is_new=True,
            ),
            400,
        )
    twitch = Twitch(
        channel_name=form.twitch_channel_name.data,
        broadcaster_id=broadcaster.id,
        twitch_username=form.twitch_username.data,
        twitch_link=form.twitch_link.data,
        author_id=current_user.id,
        tgbot_id=form.bot.data,
    )
    db_session.add(twitch)
    try:
        db_session.flush()
    except Exception as e:
        print(e)
        flash("1 бот может быть привязан только 1 каналу", category="danger")
        db_session.rollback()
        return (
            render_template(
                "panel/panel_form_twitch.html",
                current_user=current_user,
                form=form,
                form_action=form_action,
            ),
            400,
        )

    twitch_action = TwitchActions(
        twitch_id=twitch.id,
        author_id=current_user.id,
        action_name=form.twitch_action.data,
        action_text=form.twitch_action_text.data,
    )
    db_session.add(twitch_action)
    db_session.flush()

    if "twitch_action_image" in request.files:
        file = request.files["twitch_action_image"]
        # if user does not select file, browser also
        # submit an empty part without filename
        filename = tools.save_file(file=file, filename=str(str(twitch.id)))
        if not filename:
            flash("Изображение не загружено", category="warning")

    if filename:
        # add attachments
        twitch_attachment = TwitchActionsAttachments(
            twitch_action_id=twitch_action.id,
            attachment_type="image",
            attachment_filename=filename,
        )
        db_session.add(twitch_attachment)
        db_session.flush()
    try:
        db_session.commit()
    except Exception as e:
        print(e)
        db_session.rollback()
        flash(message=f"Сохранение не прошло: {e}", category="danger")
        return render_template(
            "panel/panel_form_twitch.html",
            current_user=current_user,
            form=form,
            form_action=form_action,
            is_new=True,
        )

    flash("Источник успешно добавлен", category="success")
    return redirect(url_for("panel.twitch_list"))


@app.route("/panel/twitch/edit/<int:twitch_id>/")
@login_required
def edit_twitch_source(twitch_id: int):
    twitch: Twitch = (
        db_session.query(Twitch)
        .filter(Twitch.id == twitch_id)
        .filiter(Twitch.author_id == current_user.id)
        .first()
    )
    if not twitch:
        flash("Запись не найдена", category="danger")
        return redirect(url_for("panel.twitch_list"))

    form = NewTwitchSource()
    form.bot.choices = tools.get_bots_choices(current_user_id=current_user.id)
    form.bot.default = twitch.tgbot_id
    form.process()

    form.twitch_channel_name.data = twitch.channel_name
    form.twitch_action.data = twitch.actions.action_name
    form.twitch_action_text.data = twitch.actions.action_text
    form.twitch_username.data = twitch.twitch_username
    form.twitch_link.data = twitch.twitch_link

    return render_template(
        "panel/panel_form_twitch.html",
        current_user=current_user,
        form=form,
        source={
            "id": twitch.id,
            "is_active": twitch.is_active,
            "twitch_channel_name": twitch.channel_name,
            "twitch_action_name": twitch.actions.action_name,
            "twitch_action_text": twitch.actions.action_text,
            "image": twitch.actions.attachments,
        },
    )


@app.route("/panel/twitch/edit/<int:twitch_id>/", methods=["POST"])
@login_required
def edit_twitch_source_post(twitch_id: int):
    twitch: Twitch = (
        db_session.query(Twitch)
        .filter(Twitch.id == twitch_id, Twitch.author_id == current_user.id)
        .first()
    )
    if not twitch:
        flash("Запись не найдена", category="danger")
        return redirect(f"/panel/twitch/edit/{twitch_id}/")

    form = NewTwitchSource(request.form)
    form.bot.choices = tools.get_bots_choices(current_user_id=current_user.id)
    if not form.validate():
        return (
            render_template(
                "panel/panel_form_twitch.html",
                current_user=current_user,
                form=form,
                source={
                    "id": twitch.id,
                    "is_active": twitch.is_active,
                    "twitch_channel_name": twitch.channel_name,
                    "twitch_action_name": twitch.actions.action_name,
                    "twitch_action_text": twitch.actions.action_text,
                    "image": twitch.actions.attachments,
                },
            ),
            422,
        )
    try:
        if twitch.channel_name != form.twitch_channel_name.data:
            twitch.broadcaster_id = loop.run_until_complete(
                tools.get_broadcaster(form.twitch_channel_name.data)
            ).id
        twitch.channel_name = form.twitch_channel_name.data
        twitch.is_active = True if request.form.get("is_active") else False
        twitch.actions.action_name = form.twitch_channel_name.data
        twitch.actions.action_text = form.twitch_action_text.data
        twitch.tgbot_id = int(form.bot.data)
        twitch.twitch_username = form.twitch_username.data
        twitch.twitch_link = form.twitch_link.data
        db_session.commit()

        if "twitch_action_image" in request.files:
            file = request.files["twitch_action_image"]
            # if user does not select file, browser also
            # submit an empty part without filename
            filename = tools.save_file(file=file, filename=str(twitch.id))
            if filename:
                twitch_attachment = (
                    db_session.query(TwitchActionsAttachments)
                    .filter(
                        TwitchActionsAttachments.twitch_action_id == twitch.actions.id
                    )
                    .first()
                )

                if twitch_attachment:
                    twitch_attachment.attachment_filename = filename
                    db_session.commit()
                else:
                    twitch_attachment = TwitchActionsAttachments(
                        twitch_action_id=twitch.actions.id,
                        attachment_filename=filename,
                        attachment_type="image",
                    )
                    db_session.add(twitch_attachment)
                    db_session.commit()

    except Exception as e:
        print(e)
        flash(

web/templates/panel/panel_edit_sources.html
{% extends 'base_panel.html' %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-1 text-gray-800">Редактировать источник: Twitch</h1>

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <br>
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">
                <center>{{ message }}</center>
            </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    {% if form.errors %}
        <br>
        {% for field, errors in form.errors.items() %}
            {% for error in errors %}
            <div class="alert alert-danger" role="alert">
                <center>{{ field }}: {{ error }}</center>
            </div>
            {% endfor %}
        {% endfor %}
    {% endif %}
    <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
            <div class="col-lg-6">
                <div class="p-5">
                   <form method="POST" action="/panel/twitch/edit/{{ source.id }}/" enctype="multipart/form-data">
                    <div class="mb-3">
                        <label for="exampleFormControlInput1">Имя канала</label>
                        {{ form.twitch_channel_name }}
                    </div>
                    <div class="mb-3">
                        <label for="controlUsername">Ваш username: {{ username }}</label>
                        {{ form.twitch_username }}
                    </div>
                    <div class="mb-3">
                        <label for="controlLink">Ссылка на twitch-канал: {{ username }}</label>
                        {{ form.twitch_link }}
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlSelect1">Выберите cобытие</label>
                        {{ form.twitch_action }}
                    </div>
                    <div class="mb-3">
                        <label>Выберите бота</label>
                       {{ form.bot }}
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlImage">Картинка</label>
                        <input type="file" id="exampleFormControlImage" name="twitch_action_image" accept="image/*">
                        {% if source.image %}
                            <img src="/{{ source.image.attachment_filename }}" width="200px">
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlTextarea1">Текст для пересылки боту. Доступные переменные: {{ '{{ username }}' }}, {{ '{{ twitch_link }}' }}</label>
                        {{ form.twitch_action_text }}
                    </div>
                    <div class="mb-3">
                        <label for="flexCheckDefault">Активно</label>
                        <input class="form-control" id="flexCheckDefault" type="checkbox" name="is_active" value="is_active" {% if source.is_active%}checked{% endif %}>
                    </div>
                       <br>
                    <div class="mb-3"><button class="btn btn-primary" type="submit">Сохранить</button></div>
                </form>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
{% endblock %}

web/templates/panel/panel_form_bots.html
{% extends 'base_panel.html' %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-1 text-gray-800">{% if is_new %}Добавить{% else %}Редактировать{% endif %} бота: Telegram</h1>

    <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
            <div class="col-lg-6">
                <div class="p-5">
                   <form method="POST" action="{{ form_action }}" enctype=multipart/form-data>
                    <div class="mb-3">
                        <label for="exampleFormControlInput1">Имя бота</label>
                        {{ form.bot_name }}
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlInput2">Ключ бота (Пример: 5311630810:AAHuzUOGtezAG-HBuSLaUNTrpzgadZf3YgZ)</label>
                        {{ form.bot_key }}
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlInput3">Список каналов (Пример: -1001499434368,-1022827366251)</label>
                        {{ form.bot_channels }}
                    </div>
                    {% if bot %}
                    <div class="mb-3">
                        <label for="flexCheckDefault">Активно</label>
                        <input class="form-control" id="flexCheckDefault" type="checkbox" name="is_active" value="is_active" {% if bot and bot.is_active %}checked{% endif %}>
                    </div>
                    {% endif %}
                       <br>
                    <div class="mb-3"><button class="btn btn-primary" type="submit">Сохранить</button></div>
                </form>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
{% endblock %}

web/templates/panel/panel_form_stream.html
{% extends 'base_panel.html' %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-1 text-gray-800">{% if is_new %}Добавление источника{% else %}Редактирование источника{% endif %}: {{ source_name }}</h1>
    <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
            <div class="col-lg-6">
                <div class="p-5">
                   <form method="POST" action="{{ form_action }}" enctype="multipart/form-data">
                    <div class="mb-3">
                        <label for="controlChannelName">Имя канала (не должно содержать спецсимволов)</label>
                        {{ form.channel_name }}
                    </div>
                    <div class="mb-3">
                        <label for="controlChannelLink">Ссылка на канал</label>
                        {{ form.channel_link }}
                    </div>
                    <div class="mb-3">
                        <label for="controlChannelActionType">Выберите событие</label>
                        {{ form.action_type }}
                    </div>
                    <div class="mb-3">
                        <label for="controlChannelBot">Выберите бота</label>
                       {{ form.bot }}
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlImage">Картинка</label>
                        <input type="file" id="exampleFormControlImage" name="action_image" accept="image/*">
                        {% if source and source.action_image %}
                            <img src="/{{ source.action_image }}" width="200px">
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="controlChannelActionText">Текст для пересылки боту. Доступные переменные: {{ '{{ channel_name }}' }}, {{ '{{ channel_link }}' }}</label>
                        {{ form.action_text }}
                    </div>
                    {% if source %}
                    <div class="mb-3">
                        <label for="checkIsActive">Активно</label>
                        {{ form.is_active }}
                    </div>
                    {% endif %}
                       <br>
                    <div class="mb-3"><button class="btn btn-primary" type="submit">Сохранить</button></div>
                </form>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
{% endblock %}

web/templates/panel/panel_form_twitch.html
{% extends 'base_panel.html' %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-1 text-gray-800">{% if is_new %}Добавление источника{% else %}Редактирование источника{% endif %}: Twitch.tv</h1>
    <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
            <div class="col-lg-6">
                <div class="p-5">
                   <form method="POST" action="{{ form_action }}" enctype="multipart/form-data">
                    <div class="mb-3">
                        <label for="exampleFormControlInput1">Имя канала</label>
                        {{ form.twitch_channel_name }}
                    </div>
                    <div class="mb-3">
                        <label for="controlUsername">Ваш username: {{ username }}</label>
                        {{ form.twitch_username }}
                    </div>
                    <div class="mb-3">
                        <label for="controlLink">Ссылка на twitch-канал: {{ username }}</label>
                        {{ form.twitch_link }}
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlSelect1">Выберите cобытие</label>
                        {{ form.twitch_action }}
                    </div>
                    <div class="mb-3">
                        <label>Выберите бота</label>
                       {{ form.bot }}
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlImage">Картинка</label>
                        <input type="file" id="exampleFormControlImage" name="twitch_action_image" accept="image/*">
                        {% if source and source.image %}
                            <img src="/{{ source.image.attachment_filename }}" width="200px">
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlTextarea1">Текст для пересылки боту. Доступные переменные: {{ '{{ username }}' }}, {{ '{{ twitch_link }}' }}</label>
                        {{ form.twitch_action_text }}
                    </div>
                    {% if source %}
                    <div class="mb-3">
                        <label for="flexCheckDefault">Активно</label>
                        <input class="form-control" id="flexCheckDefault" type="checkbox" name="is_active" value="is_active" {% if source.is_active%}checked{% endif %}>
                    </div>
                    {% endif %}
                       <br>
                    <div class="mb-3"><button class="btn btn-primary" type="submit">Сохранить</button></div>
                </form>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
{% endblock %}

web/templates/panel/panel_form_vkplay.html
{% extends 'base_panel.html' %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-1 text-gray-800">{% if is_new %}Добавление источника{% else %}Редактирование источника{% endif %}: VKPlay.live</h1>
    <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
            <div class="col-lg-6">
                <div class="p-5">
                   <form method="POST" action="{{ form_action }}" enctype="multipart/form-data">
                    <div class="mb-3">
                        <label for="controlChannelName">Название канала</label>
                        {{ form.channel_name }}
                    </div>
                    <div class="mb-3">
                        <label for="controlChannelLink">Ссылка на канал</label>
                        {{ form.channel_link }}
                    </div>
                    <div class="mb-3">
                        <label for="controlChannelActionType">Выберите событие</label>
                        {{ form.action_type }}
                    </div>
                    <div class="mb-3">
                        <label for="controlChannelBot">Выберите бота</label>
                       {{ form.bot }}
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlImage">Картинка</label>
                        <input type="file" id="exampleFormControlImage" name="action_image" accept="image/*">
                        {% if source and source.action_image %}
                            <img src="/{{ source.action_image }}" width="200px">
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="controlChannelActionText">Текст для пересылки боту. Доступные переменные: {{ '{{ channel_name }}' }}, {{ '{{ channel_link }}' }}</label>
                        {{ form.action_text }}
                    </div>
                    {% if source %}
                    <div class="mb-3">
                        <label for="checkIsActive">Активно</label>
                        {{ form.is_active }}
                    </div>
                    {% endif %}
                       <br>
                    <div class="mb-3"><button class="btn btn-primary" type="submit">Сохранить</button></div>
                </form>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
{% endblock %}

web/templates/panel/panel_list_bots.html
{% extends 'base_panel.html' %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">
    <center><a class="btn btn-primary" href="{{ url_for('panel.new_bots') }}">Добавить бота</a></center>

    <!-- Page Heading -->
    <h1 class="h3 mb-1 text-gray-800">Ваши боты</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">List</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Имя</th>
                            <th>Активен</th>
                            <th>Создан</th>
                            <th>Логи</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for bot in bots %}
                        <tr>
                            <td><a href="/panel/bots/edit/{{ bot.id }}/">{{ bot.name|truncate(24, True) }}</a></td>
                            <td>{{ bot.is_active }}</td>
                            <td>{{ bot.created_at }}</td>
                            <td>(available in future)</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

{% endblock %}

web/templates/panel/panel_list_streams.html
{% extends 'base_panel.html' %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">
    {% if source_type == 'vkplay' %}
        {% set new_url = url_for('panel.new_vkplay_source') %}
    {% elif source_type == 'goodgame' %}
        {% set new_url = url_for('panel.new_goodgame_source') %}
    {% endif %}
    <center><a class="btn btn-primary" href="{{ new_url }}">Добавить {{ source_name }} стрим</a></center>

    <!-- Page Heading -->
    <h1 class="h3 mb-1 text-gray-800">Ваши источники</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">List</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Имя</th>
                            <th>Live Now</th>
                            <th>Активен</th>
                            <th>Создан</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for source in sources %}
                        {% if source_type == 'vkplay' %}
                            {% set edit_url = url_for('panel.vkplay_edit', vkplay_id=source.id) %}
                        {% elif source_type == 'goodgame' %}
                            {% set edit_url = url_for('panel.edit_goodgame_source', source_id=source.id) %}
                        {% endif %}
                        <tr>
                            <td><a href="{{ edit_url }}">{{ source.channel_name|truncate(24, True) }}</a></td>
                            <td>{{ source.is_live_now }}</td>
                            <td>{{ source.is_active }}</td>
                            <td>{{ source.created_at }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

{% endblock %}

web/templates/panel/panel_list_twitch.html
{% extends 'base_panel.html' %}
{% block content %}
<!-- Begin Page Content -->

<div class="container-fluid">
    <center><a class="btn btn-primary" href="{{ url_for('panel.new_twitch_source') }}">Добавить twitch</a></center>
    <!-- Page Heading -->
    <h1 class="h3 mb-1 text-gray-800">Ваши источники</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        {% if twitch_sources %}
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Имя канала</th>
                            <th>Создан</th>
                            <th>Статус</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for twitch_source in twitch_sources %}
                        {% set webhook_key = twitch_source.id|string() + '_' + twitch_source.tgbot_id|string() %}
                        {% set button_text = 'Активировать' %}
                        {% set form_url = url_for('panel.activate_webhook') %}
                        {% if webhook_statuses[webhook_key] == 'enabled' %}
                            {% set button_text = 'Деактивировать' %}
                            {% set form_url = url_for('panel.deactivate_webhook') %}
                        {% endif %}
                        <tr>
                            <td><a href="/panel/twitch/edit/{{ twitch_source.id }}/">{{ twitch_source.channel_name|truncate(24, True) }}</a></td>
                            <td>{{ twitch_source.created_at }}</td>
                            <td>{{ webhook_statuses[webhook_key] }}</td>
                            <td align="center">
                                <form action="{{ form_url }}" method="POST">
                                    <input type="hidden" name="tgbot_id" value="{{ twitch_source.tgbot_id }}">
                                    <input type="hidden" name="twitch_id" value="{{ twitch_source.id }}">
                                    <button class="btn btn-secondary" type="submit">{{ button_text }}</button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% endif %}
    </div>

</div>
<!-- /.container-fluid -->
{% endblock %}

web/templates/panel/panel_list_vkplay.html
{% extends 'base_panel.html' %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">
    <center><a class="btn btn-primary" href="{{ url_for('panel.new_vkplay_source') }}">Добавить VKPlay.live стрим</a></center>

    <!-- Page Heading -->
    <h1 class="h3 mb-1 text-gray-800">Ваши источники</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">List</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Имя</th>
                            <th>Live Now</th>
                            <th>Активен</th>
                            <th>Создан</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for vkplay_stream in vkplay_streams %}
                        <tr>
                            <td><a href="{{ url_for('panel.vkplay_edit', vkplay_id=vkplay_stream.id) }}">{{ vkplay_stream.channel_name|truncate(24, True) }}</a></td>
                            <td>{{ vkplay_stream.is_live_now }}</td>
                            <td>{{ vkplay_stream.is_active }}</td>
                            <td>{{ vkplay_stream.created_at }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

{% endblock %}