web/views/forms/login.py
from wtforms import EmailField, Form, PasswordField
from wtforms.validators import InputRequired


class LoginForm(Form):
    email = EmailField("Email", validators=[InputRequired()])
    password = PasswordField(
        "Password",
        [InputRequired()],
    )

web/views/auth.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.security import check_password_hash, generate_password_hash

from db.pg import db_session
from models.user import Users
from web.views.forms.login import LoginForm
from web.views.forms.signup import SignupForm

app = Blueprint("auth", __name__)


@app.route("/")
def login():
    if current_user.is_authenticated:
        return redirect(url_for("panel.index"))
    form = LoginForm()
    return render_template("login.html", form=form)


@app.route("/", methods=["POST"])
def login_post():
    form = LoginForm(request.form)
    if not form.validate():
        return render_template("login.html", form=form), 422
    user: Users = (
        db_session.query(Users)
        .filter(Users.email == form.email.data, Users.is_active.is_(True))
        .first()
    )

    if not user:
        flash("Пользователь не найден", category="danger")
        return render_template("login.html", form=form), 404

    if not check_password_hash(pwhash=user.hashed_pwd, password=form.password.data):
        flash("Пароль неверный", category="danger")
        return render_template("login.html", form=form), 404

    remember = True if request.form.get("remember") else False
    login_user(user, remember=remember)

    return redirect(url_for("panel.index"))


@app.route("/signup/")
def signup_get():
    form = SignupForm()
    return render_template("register.html", form=form)


@app.route("/signup/", methods=["POST"])
def signup_post():
    form = SignupForm(request.form)
    if not form.validate():
        return render_template("register.html", form=form), 422

    if db_session.query(Users).filter(Users.email == request.form.get("email")).first():
        flash("Этот email уже занят другим пользователем", category="danger")
        return render_template("register.html", form=form), 409

    created_user = Users(
        email=form.email.data,
        hashed_pwd=generate_password_hash(password=form.password.data),
    )
    db_session.add(created_user)

    try:
        db_session.commit()
    except Exception as e:
        print(e)
        db_session.rollback()
        flash("Что-то пошло не так, обратитесь к админу", category="danger")
        return redirect(url_for("signup"))

    return redirect(url_for("panel.index"))


@app.route("/logout/")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))

web/views/panel.py
from typing import List

import httpx
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from config import config
from db.pg import db_session
from models.bots import Bots
from models.connectors import (
    GoodgameStreams,
    Twitch,
    TwitchActions,
    TwitchActionsAttachments,
    VkPlayLive,
)
from models.webhooks import Webhooks
from web.shared_loop import loop
from web.views import tools
from web.views.forms.bot import NewBotForm
from web.views.forms.new_twitch import NewTwitchSource
from web.views.forms.vkplay import BasicStreamForm

app = Blueprint("panel", __name__)


@app.route("/panel/")
@login_required
def index():
    return render_template("panel.html", current_user=current_user)


@app.route("/panel/source/twitch/")
@login_required
def twitch_list():
    limit = request.args.get("limit") or 100
    offset = request.args.get("offset") or 0
    query = (
        db_session.query(Twitch)
        .filter(Twitch.author_id == current_user.id)
        .order_by(Twitch.created_at.desc())
    )
    if limit:
        query = query.limit(limit)
    if offset:
        query = query.offset(offset)

    twitch_sources: List[Twitch] = query.all()

    if twitch_sources:
        tools.sync_webhook_statuses()

    webhook_statuses = {}
    for twitch in twitch_sources:
        webhook: Webhooks = (
            db_session.query(Webhooks)
            .filter(
                Webhooks.twitch_id == twitch.id, Webhooks.tgbot_id == twitch.tgbot_id
            )
            .first()
        )
        if not webhook:
            continue

        webhook_statuses[
            f"{webhook.twitch_id}_{webhook.tgbot_id}"
        ] = webhook.twitch_webhook_status

    return render_template(
        "panel/panel_list_twitch.html",
        current_user=current_user,
        twitch_sources=twitch_sources,
        webhook_statuses=webhook_statuses,
    )


@app.route("/panel/source/twitch/new/")
@login_required
def new_twitch_source():
    form = NewTwitchSource()
    form.bot.choices = tools.get_bots_choices(current_user_id=current_user.id)
    form_action = url_for("panel.new_twitch_source_post")
    return render_template(
        "panel/panel_form_twitch.html",
        current_user=current_user,
        form=form,
        form_action=form_action,
        is_new=True,
    )


@app.route("/panel/twitch/new/", methods=["POST"])
@login_required
def new_twitch_source_post():
    form = NewTwitchSource(request.form)
    form.bot.choices = tools.get_bots_choices(current_user_id=current_user.id)
    form_action = url_for("panel.new_twitch_source_post")
    if not form.validate():
        return (
            render_template(
                "panel/panel_form_twitch.html",
                current_user=current_user,
                form=form,
                form_action=form_action,
                is_new=True,
            ),
            422,
        )

    filename = None

    broadcaster = loop.run_until_complete(
        tools.get_broadcaster(form.twitch_channel_name.data)
    )
    if not broadcaster:
        flash("Ваш broadcaster.id (twitch) не найден", category="danger")
        return (
            render_template(
                "panel/panel_form_twitch.html",
                current_user=current_user,
                form=form,
                form_action=form_action,
                is_new=True,
            ),
            400,
        )
    twitch = Twitch(
        channel_name=form.twitch_channel_name.data,
        broadcaster_id=broadcaster.id,
        twitch_username=form.twitch_username.data,
        twitch_link=form.twitch_link.data,
        author_id=current_user.id,
        tgbot_id=form.bot.data,
    )
    db_session.add(twitch)
    try:
        db_session.flush()
    except Exception as e:
        print(e)
        flash("1 бот может быть привязан только 1 каналу", category="danger")
        db_session.rollback()
        return (
            render_template(
                "panel/panel_form_twitch.html",
                current_user=current_user,
                form=form,
                form_action=form_action,
            ),
            400,
        )

    twitch_action = TwitchActions(
        twitch_id=twitch.id,
        author_id=current_user.id,
        action_name=form.twitch_action.data,
        action_text=form.twitch_action_text.data,
    )
    db_session.add(twitch_action)
    db_session.flush()

    if "twitch_action_image" in request.files:
        file = request.files["twitch_action_image"]
        # if user does not select file, browser also
        # submit an empty part without filename
        filename = tools.save_file(file=file, filename=str(str(twitch.id)))
        if not filename:
            flash("Изображение не загружено", category="warning")

    if filename:
        # add attachments
        twitch_attachment = TwitchActionsAttachments(
            twitch_action_id=twitch_action.id,
            attachment_type="image",
            attachment_filename=filename,
        )
        db_session.add(twitch_attachment)
        db_session.flush()
    try:
        db_session.commit()
    except Exception as e:
        print(e)
        db_session.rollback()
        flash(message=f"Сохранение не прошло: {e}", category="danger")
        return render_template(
            "panel/panel_form_twitch.html",
            current_user=current_user,
            form=form,
            form_action=form_action,
            is_new=True,
        )

    flash("Источник успешно добавлен", category="success")
    return redirect(url_for("panel.twitch_list"))


@app.route("/panel/twitch/edit/<int:twitch_id>/")
@login_required
def edit_twitch_source(twitch_id: int):
    twitch: Twitch = (
        db_session.query(Twitch)
        .filter(Twitch.id == twitch_id)
        .filiter(Twitch.author_id == current_user.id)
        .first()
    )
    if not twitch:
        flash("Запись не найдена", category="danger")
        return redirect(url_for("panel.twitch_list"))

    form = NewTwitchSource()
    form.bot.choices = tools.get_bots_choices(current_user_id=current_user.id)
    form.bot.default = twitch.tgbot_id
    form.process()

    form.twitch_channel_name.data = twitch.channel_name
    form.twitch_action.data = twitch.actions.action_name
    form.twitch_action_text.data = twitch.actions.action_text
    form.twitch_username.data = twitch.twitch_username
    form.twitch_link.data = twitch.twitch_link

    return render_template(
        "panel/panel_form_twitch.html",
        current_user=current_user,
        form=form,
        source={
            "id": twitch.id,
            "is_active": twitch.is_active,
            "twitch_channel_name": twitch.channel_name,
            "twitch_action_name": twitch.actions.action_name,
            "twitch_action_text": twitch.actions.action_text,
            "image": twitch.actions.attachments,
        },
    )


@app.route("/panel/twitch/edit/<int:twitch_id>/", methods=["POST"])
@login_required
def edit_twitch_source_post(twitch_id: int):
    twitch: Twitch = (
        db_session.query(Twitch)
        .filter(Twitch.id == twitch_id, Twitch.author_id == current_user.id)
        .first()
    )
    if not twitch:
        flash("Запись не найдена", category="danger")
        return redirect(f"/panel/twitch/edit/{twitch_id}/")

    form = NewTwitchSource(request.form)
    form.bot.choices = tools.get_bots_choices(current_user_id=current_user.id)
    if not form.validate():
        return (
            render_template(
                "panel/panel_form_twitch.html",
                current_user=current_user,
                form=form,
                source={
                    "id": twitch.id,
                    "is_active": twitch.is_active,
                    "twitch_channel_name": twitch.channel_name,
                    "twitch_action_name": twitch.actions.action_name,
                    "twitch_action_text": twitch.actions.action_text,
                    "image": twitch.actions.attachments,
                },
            ),
            422,
        )
    try:
        if twitch.channel_name != form.twitch_channel_name.data:
            twitch.broadcaster_id = loop.run_until_complete(
                tools.get_broadcaster(form.twitch_channel_name.data)
            ).id
        twitch.channel_name = form.twitch_channel_name.data
        twitch.is_active = True if request.form.get("is_active") else False
        twitch.actions.action_name = form.twitch_channel_name.data
        twitch.actions.action_text = form.twitch_action_text.data
        twitch.tgbot_id = int(form.bot.data)
        twitch.twitch_username = form.twitch_username.data
        twitch.twitch_link = form.twitch_link.data
        db_session.commit()

        if "twitch_action_image" in request.files:
            file = request.files["twitch_action_image"]
            # if user does not select file, browser also
            # submit an empty part without filename
            filename = tools.save_file(file=file, filename=str(twitch.id))
            if filename:
                twitch_attachment = (
                    db_session.query(TwitchActionsAttachments)
                    .filter(
                        TwitchActionsAttachments.twitch_action_id == twitch.actions.id
                    )
                    .first()
                )

                if twitch_attachment:
                    twitch_attachment.attachment_filename = filename
                    db_session.commit()
                else:
                    twitch_attachment = TwitchActionsAttachments(
                        twitch_action_id=twitch.actions.id,
                        attachment_filename=filename,
                        attachment_type="image",
                    )
                    db_session.add(twitch_attachment)
                    db_session.commit()

    except Exception as e:
        print(e)
        flash(

web/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Custom fonts for this template-->
    <link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="/static/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">
    {% block messages %}
        {% include 'include/messages.html' %}
    {% endblock %}
    {% block content %}
    {% endblock %}
    {% block footer %}
    <!-- Bootstrap core JavaScript-->
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="/static/js/sb-admin-2.min.js"></script>
    {% endblock %}
</body>

web/templates/base_panel.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin</title>

    <!-- Custom fonts for this template-->
    <link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="/static/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        {% include 'include/menu.html' %}

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    {% include 'include/top_user.html' %}

                </nav>
                <!-- End of Topbar -->

                {% include 'include/messages.html' %}
                {% block content %}
                {% endblock %}
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            {% include 'include/footer.html' %}
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript-->
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="/static/js/sb-admin-2.min.js"></script>

</body>

</html>

web/templates/login.html
{% extends 'base.html' %}
{% block title %}Логин{% endblock %}
{% block content %}
    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Привет!</h1>
                                    </div>
                                    <form class="user" action="{{ url_for('auth.login_post') }}" method="POST">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp"
                                                placeholder="Ваш email..." name="email">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                id="exampleInputPassword" placeholder="Password" name="password">
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="customCheck" name="remember">
                                                <label class="custom-control-label" for="customCheck">Запомнить</label>
                                            </div>
                                        </div>
                                        <button class="btn btn-primary btn-user btn-block">
                                            Login
                                        </button>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="#">Забыли пароль?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="{{ url_for('auth.signup_get') }}">Создать аккаунт!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
{% endblock %}

web/templates/panel.html
{% extends 'base_panel.html' %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-1 text-gray-800">Telegram Notifier</h1>
    <p class="mb-4">Сервис для пересылки сообщений и оповещений о стримах (поддерживаются платформы: twitch.tv, vkplay.live) в Telegram чат/канал, Discord</p>

</div>
<!-- /.container-fluid -->
{% endblock %}

web/templates/panel_edit_bots.html
{% extends 'base_panel.html' %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-1 text-gray-800">Редактировать бота: Telegram</h1>

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <br>
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">
                <center>{{ message }}</center>
            </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    {% if form.errors %}
        <br>
        {% for field, errors in form.errors.items() %}
            {% for error in errors %}
            <div class="alert alert-danger" role="alert">
                <center>{{ field }}: {{ error }}</center>
            </div>
            {% endfor %}
        {% endfor %}
    {% endif %}
    <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
            <div class="col-lg-6">
                <div class="p-5">
                   <form method="POST" action="/panel/bots/edit/{{ bot.id }}/" enctype=multipart/form-data>
                    <div class="mb-3">
                        <label for="exampleFormControlInput1">Имя бота</label>
                        {{ form.bot_name }}
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlInput2">Ключ бота (Пример: 5311630810:AAHuzUOGtezAG-HBuSLaUNTrpzgadZf3YgZ)</label>
                        {{ form.bot_key }}
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlInput3">Список каналов (Пример: -1001499434368,-1022827366251)</label>
                        {{ form.bot_channels }}
                    </div>
                    <div class="mb-3">
                        <label for="flexCheckDefault">Активно</label>
                        <input class="form-control" id="flexCheckDefault" type="checkbox" name="is_active" value="is_active" {% if bot.is_active %}checked{% endif %}>
                    </div>
                       <br>
                    <div class="mb-3"><button class="btn btn-primary" type="submit">Сохранить</button></div>
                </form>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
{% endblock %}

web/templates/panel_list_bots.html
{% extends 'base_panel.html' %}
{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <br>
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">
                <center>{{ message }}</center>
            </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    <a class="btn btn-primary" href="/panel/bots/new/">Добавить бота</a>

    <!-- Page Heading -->
    <h1 class="h3 mb-1 text-gray-800">Ваши боты</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">List</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Имя</th>
                            <th>Активен</th>
                            <th>Создан</th>
                            <th>Логи</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for bot in bots %}
                        <tr>
                            <td><a href="/panel/bots/edit/{{ bot.id }}/">{{ bot.name|truncate(24, True) }}</a></td>
                            <td>{{ bot.is_active }}</td>
                            <td>{{ bot.created_at }}</td>
                            <td>(available in future)</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

{% endblock %}

web/templates/panel_list_sources.html
{% extends 'base_panel.html' %}
{% block content %}
<!-- Begin Page Content -->

<div class="container-fluid">
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <br>
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">
                <center>{{ message }}</center>
            </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

    <a class="btn btn-primary" href="/panel/twitch/new/">Добавить twitch</a>
    <!-- Page Heading -->
    <h1 class="h3 mb-1 text-gray-800">Ваши источники</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        {% if twitch_sources %}
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Имя канала</th>
                            <th>Создан</th>
                            <th>Статус</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for twitch_source in twitch_sources %}
                        {% set webhook_key = twitch_source.id|string() + '_' + twitch_source.tgbot_id|string() %}
                        {% set button_text = 'Активировать' %}
                        {% set form_url = url_for('panel.activate_webhook') %}
                        {% if webhook_statuses[webhook_key] == 'enabled' %}
                            {% set button_text = 'Деактивировать' %}
                            {% set form_url = url_for('panel.deactivate_webhook') %}
                        {% endif %}
                        <tr>
                            <td><a href="/panel/twitch/edit/{{ twitch_source.id }}/">{{ twitch_source.channel_name|truncate(24, True) }}</a></td>
                            <td>{{ twitch_source.created_at }}</td>
                            <td>{{ webhook_statuses[webhook_key] }}</td>
                            <td align="center">
                                <form action="{{ form_url }}" method="POST">
                                    <input type="hidden" name="tgbot_id" value="{{ twitch_source.tgbot_id }}">
                                    <input type="hidden" name="twitch_id" value="{{ twitch_source.id }}">
                                    <button class="btn btn-secondary" type="submit">{{ button_text }}</button>
                                </form>
</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% endif %}
    </div>

</div>
<!-- /.container-fluid -->
{% endblock %}

web/templates/register.html
{% extends 'base.html' %}
{% block title %}Регистрация{% endblock %}
{% block content %}
    <div class="container">
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Регистрация</h1>
                            </div>
                            <form class="user" action="{{ url_for('auth.signup_post') }}" method="POST">
                                <div class="form-group">
                                    <input type="email" class="form-control form-control-user" id="exampleInputEmail"
                                        placeholder="Email адрес" name="email">
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="password" class="form-control form-control-user"
                                            id="exampleInputPassword" placeholder="Пароль" name="password">
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="password" class="form-control form-control-user"
                                            id="exampleRepeatPassword" placeholder="Повторите пароль" name="confirm_password">
                                    </div>
                                </div>
                                <button class="btn btn-primary btn-user btn-block">
                                    Register Account
                                </button>
                            </form>
                            <hr>
                            <div class="text-center">
                                <a class="small" href="#">Забыли пароль?</a>
                            </div>
                            <div class="text-center">
                                <a class="small" href="{{ url_for('auth.login') }}">Уже есть аккаунт? Залогиньтесь!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}