web/views/panel.py
from typing import List

import httpx
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from config import config
from db.pg import db_session
from models.bots import Bots
from models.connectors import (
    GoodgameStreams,
    Twitch,
    TwitchActions,
    TwitchActionsAttachments,
    VkPlayLive,
)
from models.webhooks import Webhooks
from web.shared_loop import loop
from web.views import tools
from web.views.forms.bot import NewBotForm
from web.views.forms.new_twitch import NewTwitchSource
from web.views.forms.vkplay import BasicStreamForm

app = Blueprint("panel", __name__)


@app.route("/panel/")
@login_required
def index():
    return render_template("panel.html", current_user=current_user)


@app.route("/panel/source/twitch/")
@login_required
def twitch_list():
    limit = request.args.get("limit") or 100
    offset = request.args.get("offset") or 0
    query = (
        db_session.query(Twitch)
        .filter(Twitch.author_id == current_user.id)
        .order_by(Twitch.created_at.desc())
    )
    if limit:
        query = query.limit(limit)
    if offset:
        query = query.offset(offset)

    twitch_sources: List[Twitch] = query.all()

    if twitch_sources:
        tools.sync_webhook_statuses()

    webhook_statuses = {}
    for twitch in twitch_sources:
        webhook: Webhooks = (
            db_session.query(Webhooks)
            .filter(
                Webhooks.twitch_id == twitch.id, Webhooks.tgbot_id == twitch.tgbot_id
            )
            .first()
        )
        if not webhook:
            continue

        webhook_statuses[
            f"{webhook.twitch_id}_{webhook.tgbot_id}"
        ] = webhook.twitch_webhook_status

    return render_template(
        "panel/panel_list_twitch.html",
        current_user=current_user,
        twitch_sources=twitch_sources,
        webhook_statuses=webhook_statuses,
    )


@app.route("/panel/source/twitch/new/")
@login_required
def new_twitch_source():
    form = NewTwitchSource()
    form.bot.choices = tools.get_bots_choices(current_user_id=current_user.id)
    form_action = url_for("panel.new_twitch_source_post")
    return render_template(
        "panel/panel_form_twitch.html",
        current_user=current_user,
        form=form,
        form_action=form_action,
        is_new=True,
    )


@app.route("/panel/twitch/new/", methods=["POST"])
@login_required
def new_twitch_source_post():
    form = NewTwitchSource(request.form)
    form.bot.choices = tools.get_bots_choices(current_user_id=current_user.id)
    form_action = url_for("panel.new_twitch_source_post")
    if not form.validate():
        return (
            render_template(
                "panel/panel_form_twitch.html",
                current_user=current_user,
                form=form,
                form_action=form_action,
                is_new=True,
            ),
            422,
        )

    filename = None

    broadcaster = loop.run_until_complete(
        tools.get_broadcaster(form.twitch_channel_name.data)
    )
    if not broadcaster:
        flash("Ваш broadcaster.id (twitch) не найден", category="danger")
        return (
            render_template(
                "panel/panel_form_twitch.html",
                current_user=current_user,
                form=form,
                form_action=form_action,
                is_new=True,
            ),
            400,
        )
    twitch = Twitch(
        channel_name=form.twitch_channel_name.data,
        broadcaster_id=broadcaster.id,
        twitch_username=form.twitch_username.data,
        twitch_link=form.twitch_link.data,
        author_id=current_user.id,
        tgbot_id=form.bot.data,
    )
    db_session.add(twitch)
    try:
        db_session.flush()
    except Exception as e:
        print(e)
        flash("1 бот может быть привязан только 1 каналу", category="danger")
        db_session.rollback()
        return (
            render_template(
                "panel/panel_form_twitch.html",
                current_user=current_user,
                form=form,
                form_action=form_action,
            ),
            400,
        )

    twitch_action = TwitchActions(
        twitch_id=twitch.id,
        author_id=current_user.id,
        action_name=form.twitch_action.data,
        action_text=form.twitch_action_text.data,
    )
    db_session.add(twitch_action)
    db_session.flush()

    if "twitch_action_image" in request.files:
        file = request.files["twitch_action_image"]
        # if user does not select file, browser also
        # submit an empty part without filename
        filename = tools.save_file(file=file, filename=str(str(twitch.id)))
        if not filename:
            flash("Изображение не загружено", category="warning")

    if filename:
        # add attachments
        twitch_attachment = TwitchActionsAttachments(
            twitch_action_id=twitch_action.id,
            attachment_type="image",
            attachment_filename=filename,
        )
        db_session.add(twitch_attachment)
        db_session.flush()
    try:
        db_session.commit()
    except Exception as e:
        print(e)
        db_session.rollback()
        flash(message=f"Сохранение не прошло: {e}", category="danger")
        return render_template(
            "panel/panel_form_twitch.html",
            current_user=current_user,
            form=form,
            form_action=form_action,
            is_new=True,
        )

    flash("Источник успешно добавлен", category="success")
    return redirect(url_for("panel.twitch_list"))


@app.route("/panel/twitch/edit/<int:twitch_id>/")
@login_required
def edit_twitch_source(twitch_id: int):
    twitch: Twitch = (
        db_session.query(Twitch)
        .filter(Twitch.id == twitch_id)
        .filiter(Twitch.author_id == current_user.id)
        .first()
    )
    if not twitch:
        flash("Запись не найдена", category="danger")
        return redirect(url_for("panel.twitch_list"))

    form = NewTwitchSource()
    form.bot.choices = tools.get_bots_choices(current_user_id=current_user.id)
    form.bot.default = twitch.tgbot_id
    form.process()

    form.twitch_channel_name.data = twitch.channel_name
    form.twitch_action.data = twitch.actions.action_name
    form.twitch_action_text.data = twitch.actions.action_text
    form.twitch_username.data = twitch.twitch_username
    form.twitch_link.data = twitch.twitch_link

    return render_template(
        "panel/panel_form_twitch.html",
        current_user=current_user,
        form=form,
        source={
            "id": twitch.id,
            "is_active": twitch.is_active,
            "twitch_channel_name": twitch.channel_name,
            "twitch_action_name": twitch.actions.action_name,
            "twitch_action_text": twitch.actions.action_text,
            "image": twitch.actions.attachments,
        },
    )


@app.route("/panel/twitch/edit/<int:twitch_id>/", methods=["POST"])
@login_required
def edit_twitch_source_post(twitch_id: int):
    twitch: Twitch = (
        db_session.query(Twitch)
        .filter(Twitch.id == twitch_id, Twitch.author_id == current_user.id)
        .first()
    )
    if not twitch:
        flash("Запись не найдена", category="danger")
        return redirect(f"/panel/twitch/edit/{twitch_id}/")

    form = NewTwitchSource(request.form)
    form.bot.choices = tools.get_bots_choices(current_user_id=current_user.id)
    if not form.validate():
        return (
            render_template(
                "panel/panel_form_twitch.html",
                current_user=current_user,
                form=form,
                source={
                    "id": twitch.id,
                    "is_active": twitch.is_active,
                    "twitch_channel_name": twitch.channel_name,
                    "twitch_action_name": twitch.actions.action_name,
                    "twitch_action_text": twitch.actions.action_text,
                    "image": twitch.actions.attachments,
                },
            ),
            422,
        )
    try:
        if twitch.channel_name != form.twitch_channel_name.data:
            twitch.broadcaster_id = loop.run_until_complete(
                tools.get_broadcaster(form.twitch_channel_name.data)
            ).id
        twitch.channel_name = form.twitch_channel_name.data
        twitch.is_active = True if request.form.get("is_active") else False
        twitch.actions.action_name = form.twitch_channel_name.data
        twitch.actions.action_text = form.twitch_action_text.data
        twitch.tgbot_id = int(form.bot.data)
        twitch.twitch_username = form.twitch_username.data
        twitch.twitch_link = form.twitch_link.data
        db_session.commit()

        if "twitch_action_image" in request.files:
            file = request.files["twitch_action_image"]
            # if user does not select file, browser also
            # submit an empty part without filename
            filename = tools.save_file(file=file, filename=str(twitch.id))
            if filename:
                twitch_attachment = (
                    db_session.query(TwitchActionsAttachments)
                    .filter(
                        TwitchActionsAttachments.twitch_action_id == twitch.actions.id
                    )
                    .first()
                )

                if twitch_attachment:
                    twitch_attachment.attachment_filename = filename
                    db_session.commit()
                else:
                    twitch_attachment = TwitchActionsAttachments(
                        twitch_action_id=twitch.actions.id,
                        attachment_filename=filename,
                        attachment_type="image",
                    )
                    db_session.add(twitch_attachment)
                    db_session.commit()

    except Exception as e:
        print(e)
        flash(

web/templates/include/footer.html
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Stream-Helper.ru 2022</span>
        </div>
    </div>
</footer>

web/templates/include/menu.html
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/panel/">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">TG-Notifier <sup>v1 (beta)</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a class="nav-link" href="{{ url_for('panel.index') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Главная</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Источники трансляций
    </div>
    <li class="nav-item">
        <a class="nav-link" href="{{ url_for('panel.twitch_list') }}">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Twitch.tv</span></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{ url_for('panel.vkplay_list') }}">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>VK Play Live</span></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{ url_for('panel.goodgame_list') }}">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>GoodGame</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Боты
    </div>

    <!-- Nav Item - Charts -->
    <li class="nav-item">
        <a class="nav-link" href="{{ url_for('panel.list_bots') }}">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Telegram-бот</span></a>
    </li>

    <!-- Nav Item - Charts -->
    <li class="nav-item">
        <a class="nav-link" href="#">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Discord-бот</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <li class="nav-item">
        <a class="nav-link" href="/logout/">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Выйти</span></a>
    </li>

</ul>
<!-- End of Sidebar -->

web/templates/include/messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      <br>
      {% for category, message in messages %}
          <div class="alert alert-{{ category }}" role="alert">
              <center>{{ message }}</center>
          </div>
      {% endfor %}
    {% endif %}
  {% endwith %}


{% if form and form.errors %}
  <br>
  {% for _, errors in form.errors.items() %}
      {% for error in errors %}
      <div class="alert alert-danger" role="alert">
          <center>{{ error }}</center>
      </div>
      {% endfor %}
  {% endfor %}
{% endif %}

web/templates/include/top_user.html
 <!-- Topbar Navbar -->
<ul class="navbar-nav ml-auto">
    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ current_user.email }}</span>
            <img class="img-profile rounded-circle"
                src="/static/img/undraw_profile.svg">
        </a>
    </li>

</ul>